### ISSUE TITLE
No Chat Tab on the Home page

### ISSUE THREAD

**Issue by ghost** [jnadaud/grav-plugin-gitter#1]
So, I've setup the plugin with the following ... 

enabled: true

enable_on_routes:
- /

disable_on_routes:
- /

Which as I suspected, enables the chat tab for all pages, but it doesn't show on the Home page.

Suggestions?

Brian U.

**Comment by jnadaud** [comment]
Hi, 

well 

```
disable_on_routes:
- /
```

will disable chat on all routes.
Also, have setup correctly your Gitter channel ?
Please see screenshots:

![screenshot 2015-11-03 09 46 23](https://cloud.githubusercontent.com/assets/4747745/10904057/5ea0795e-8210-11e5-8562-fa8e2eb8c464.png)
![screenshot 2015-11-03 09 46 42](https://cloud.githubusercontent.com/assets/4747745/10904058/5ec0fce2-8210-11e5-9518-2a9714c94f94.png)
![screenshot 2015-11-03 09 47 27](https://cloud.githubusercontent.com/assets/4747745/10904059/5ec4cd90-8210-11e5-81b7-5fc458631585.png)

**Comment by jnadaud** [comment]
Hi @umbergerba,

Did you still have the problem ?

Best regards

**Comment by ghost** [comment]
I fixed the issue with the following change ...

disable_on_routes:
-/x

THX for the help!

Brian U.

**Comment by jnadaud** [comment]
Great !

Best regards.
